=== thanhdatpb/XML_HUSC/Hoa_don.dtd
<!ELEMENT HOADON (TIEUDE, SOHOADON, HOVATEN, NGAYLAP, BANGHOADON)>
<!ELEMENT TIEUDE (#PCDATA)>
<!ELEMENT SOHOADON (#PCDATA)>
<!ELEMENT HOVATEN (#PCDATA)>
<!ELEMENT NGAYLAP (#PCDATA)>
<!ELEMENT BANGHOADON (DICHVU+, TONGTIEN)>
<!ELEMENT DICHVU (#PCDATA)>
<!ELEMENT TONGTIEN (#PCDATA)>

<!ATTLIST DICHVU 
    Ten CDATA #REQUIRED
    Loai CDATA #REQUIRED
    SoLuong CDATA #REQUIRED
    DonGia CDATA #REQUIRED
    ThanhTien CDATA #REQUIRED>

=== thanhdatpb/XML_HUSC/Hoa_don.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HOADON PUBLIC "public-id" "Hoa_don.dtd">
<HOADON>
    <TIEUDE>HÓA ĐƠN THANH TOÁN</TIEUDE>
    <SOHOADON>12345</SOHOADON>
    <HOVATEN>NGUYỄN VĂN A</HOVATEN>
    <NGAYLAP>01/06/2020</NGAYLAP>

    <BANGHOADON>
        <DICHVU 
            Ten="Thuê phòng" 
            Loai="A" 
            SoLuong="4 ngày" 
            DonGia="600.000 đ" 
            ThanhTien="2.400.000 đ"
        />
        <DICHVU 
            Ten="Thuê phòng" 
            Loai="4 chỗ" 
            SoLuong="5 giờ" 
            DonGia="150.000 đ" 
            ThanhTien="750.000 đ"
        />
    <TONGTIEN>3.650.000</TONGTIEN>
    </BANGHOADON>
</HOADON>
